### ISSUE TITLE
Automatic scanning of repository branches

### ISSUE THREAD

**Issue by gotec** [gotec/git2net#12]
Add example on how multiple branches of a repository can be mined to the tutorial. Something similar to the code below should do the trick.

```
from git import Git
import git2net

gr =Git('git_repo_dir')
for branch in gr.branches()
    gr.checkout(branch)
    git2net.mine_git_repo('git_repo_dir', 'sqlite_db_file")
```

**Comment by SebastianZug** [comment]
Hi gotec,

two questions related to the scanning process:
1. What kind of result do you expect? I guess the git activities should be merged in one database at the end. What’s the best way to realize this? Your implementation do not include a `append` method ... 
2. Should we focus on remote or local branches in the example?

Sebastian

```python
import git
import os
import shutil
import git2net

git_repo_url = 'https://github.com/gotec/git2net.git'
local_directory = '.'
git_repo_dir = './git2net4analysis'

# 1. Clone the repo
if os.path.exists(git_repo_dir):
    shutil.rmtree(git_repo_dir)
repo = git.Repo.clone_from(git_repo_url, git_repo_dir)

# 2. Determine remote branches 
remote_refs = repo.remote().refs
repo_branch_names = []
for ref in remote_refs:
    branch_name = ref.name.split('/')[-1]
    if branch_name != 'HEAD':
        repo_branch_names.append(branch_name)
print("{} branches found ".format(len(repo_branch_names)))

# 3. Iterating branches and generating db files
for branch in repo_branch_names:
    repo.git.checkout(branch)
    sqlite_db_file = 'git2net_' + branch + '.db'
    if os.path.exists(sqlite_db_file):
        os.remove(sqlite_db_file)
    git2net.mine_git_repo(git_repo_dir, sqlite_db_file)

**Comment by gotec** [comment]
Hi Sebastian

Thank you for the questions as well as the example!

1. I agree that the activities should be merged in a single database. Unfortunately a simple append method would likely not fully solve this as ideally commits that were already mined in the main branch (or any previously mined branch for that matter) would not meed to be mined again.
2. Ideally remote branches although in that case the git2net example can no longer be used. Another good point to think about.

I will look into this over the weekend and get back to you.

Christoph

**Comment by SebastianZug** [comment]
Hi Christoph,

we can avoid duplicates by appending the name of the branch if the commit already exists. In this way we should have a "InMainBranch" (Yes, No) as well as "ContainingBranches" {featureA, BugFixB, TestingC}. Following this idea we can easily filter all commits in the main branch but identify non merged commits too.

Sebastian

**Comment by gotec** [comment]
Hi Sebastian,

Yes, this is exactly what I am planning to implement. To this end we first need to find out which branch is currently checked out and before starting the mining process all commits that are already in the database need to have this new branch attached. I also agree with the idea of python set syntax in the `ContainingBranches` field as it easily allows to read the data from sqlite with the `ast.literal_eval` or something similar.

I have further implemented a function `mine_github()` that allows to directly clone and mine a project from GitHub. As this function allows to specify the branch being able to properly store the resulting data would also be useful here. The function might also be interesting for you in case your repositories are publicly available.

Best,
Christoph

**Comment by SebastianZug** [comment]
Hi Christoph,

the direct mining feature is cool, but due to the fact that our student accounts are private, I prefer to generate a local clone. Should I provide a short explanation how token based access can be realized based on pygit. In this way the tutorial would cover both configurations.

Sebastian

**Comment by gotec** [comment]
Hi Sebastian,

Thanks for offering that. Of course that would be great and very helpful for everyone in your situation in the future. I would very much appreciate the explanation!

Best,
Christoph

**Comment by gotec** [comment]
Hi Sebastian,

I have updated the `mine_github()` function to be able to continue mining different branches after finishing the first one.
Note that I have not fully tested the new function yet so if you find any issues please let me know. I am currently aware of the following:

1. As it can now happen that the current branch contains different (fewer) commits than in the database I have updated the corresponding check accordingly. To still provide some safety for users, I am now matching the upstream url of the cloned repository to the one listed in the database. As this was previously not recorded you will need to update this entry manually in the repositories you have already mined in order to continue with the branches.
2. The entries in `branches` in the commits table are comma separated and not in python set syntax as you proposed. I have made this decision to maintain interoperability with old databases.
3. Even for commits that are not in the main branch the column `in_main_branch` is always 1. I will open a ticket with the developers of PyDriller to understand why this is the case.
4. As the function is not yet fully tested I have opted to not make a release on PyPI yet. Instead all code is available in the newly created `mining_branches` branch of git2net. You can install it with `pip install -e .` from within the folder of the cloned repository.

Best,
Christoph

**Comment by gotec** [comment]
Hi Sebastian,

Thanks a lot for the very nice additions to the tutorial!

I have some updates regarding the mining of branches also from my discussions with Davide Spadini, the developer of pyDriller:

1. The method described in https://github.com/gotec/git2net/issues/12#issuecomment-667695308 to mine different branches works nicely but there is no easy way to make `in_main_branch` only show 1 for the default branch. The reason for this is that the main branch is always the currently active branch. As we are checking out each branch after each other the currently mined branch is always considered the main branch. Thus, the results will be correct as long as you ignore this branch in the final database.
2. We have also identified a method that allows all branches of a repository to be mined at once. To do this, first all branches of a repository need to be tracked. This can be done following [this](https://stackoverflow.com/a/40318872) guide on stackoverflow. Now you should be in the default branch of your cloned repository but all other branches are also available to you locally.
You can now mine this repository with git2net and obtain the correct list of branches in which all commits from the default branch appear. Commits that are only present in branches will not be mined. To also include those you need to run git2net with the `all_branches=True` option available in the mining_branches branch.
Following this approach you will receive a database with all commits from a single mining process. Also, the `in_main_branch` indicator will work as expected as the repository is mined from the default branch.

I hope this solves the issue with your projects. I will try to come up with a method that will allow this to be used more easily in the future. For the `mine_github` function this is not an issue but conveniently integrating it into the `mine_git_repo` function will be a bit more challenging.

Best,
Christoph

**Comment by SebastianZug** [comment]
Hi Christoph,

I wrote a small test tool for evaluating the current implementation:

```python
#!/usr/bin/env python
# coding: utf-8

# Step 1: Clone repository
import pygit2 as git2
import os
import shutil

git_repo_url = 'https://github.com/gotec/git2net.git'
local_directory = '.'
git_repo_dir = 'git2net4analysis'

if os.path.exists(git_repo_dir):
    shutil.rmtree(git_repo_dir)

repo = git2.clone_repository(git_repo_url, git_repo_dir) 

# Step 2: Crawl the local repository

import git2net
import os

sqlite_db_file = 'git2net.db'

if os.path.exists(sqlite_db_file):
    os.remove(sqlite_db_file) 
git2net.mine_git_repo(git_repo_dir, sqlite_db_file, all_branches=True, max_modifications=5)

# Step 3: Check the covered branches

import sqlite3
import pandas as pd
import glob

pdCommits = pd.DataFrame()
db = sqlite3.connect(sqlite_db_file)
pdTeamCommits = pd.read_sql_query("SELECT * FROM commits", db)
pdCommits = pdCommits.append(pdTeamCommits, ignore_index = True)

pdCommits.branches.value_counts()
```

Unfortunately, the output is 

```
master    191
                   4
Name: branches, dtype: int64 
```

illustrating that 4 commits from "unknown branches" appear beside 191 from master. Did I misunderstand your documentation?

Best wishes!

Sebastian

**Comment by gotec** [comment]
Hi Sebastian,

sorry for the delayed response. I was on holiday during the last 2 weeks and must have missed the notification email.

I think the issue is with your clone of the repository. By "just" cloning  the repository, git does not track all branches. This can be achieved by executing `git branch --track ${branch#remotes/origin/} $branch` for all branches before mining the repository. Otherwise the branches corresponding to the commits are indeed unknown.
This is fully detailed in the stackoverflow that I linked (https://stackoverflow.com/a/40318872). I will try to find out how that can be done from within python later today and update your implementation then.

Best,
Christoph

**Comment by gotec** [comment]
Hi Sebastian,

the following code should do the trick.

```python
# Step 1: Clone repository

import git
import os
import shutil

git_repo_url = 'https://github.com/gotec/git2net.git'
local_directory = '.'
git_repo_dir = 'git2net4analysis'

if os.path.exists(git_repo_dir):
    shutil.rmtree(git_repo_dir)

repo = git.Repo.clone_from(git_repo_url, git_repo_dir)



# Step 2: Track remote branches

existing_branches = [b.name for b in repo.branches]
for ref in repo.remote().refs:
    branch_name = ref.name.split('/')[-1]
    if branch_name != 'HEAD' and branch_name not in existing_branches:
        repo.git.branch('--track', branch_name, 'remotes/origin/'+branch_name)

        
        
# Step 3: Crawl the local repository

import git2net
import os

sqlite_db_file = 'git2net.db'

if os.path.exists(sqlite_db_file):
    os.remove(sqlite_db_file) 
git2net.mine_git_repo(git_repo_dir, sqlite_db_file, all_branches=True)



# Step 4: Check the covered branches

import sqlite3
import pandas as pd
import glob

pdCommits = pd.DataFrame()
db = sqlite3.connect(sqlite_db_file)
pdTeamCommits = pd.read_sql_query("SELECT * FROM commits", db)
pdCommits = pdCommits.append(pdTeamCommits, ignore_index = True)

pdCommits.branches.value_counts()
```

For me it returns

```
mining_branches,master                          105
add-code-of-conduct-1,mining_branches,master     87
master                                            5
add-code-of-conduct-1                             1
```

and hence exactly what I would expect.

Best,
Christoph

**Comment by SebastianZug** [comment]
Yup! Now it works

**Comment by gotec** [comment]
That's great to hear! In that case it would probably be best to add it to both the tutorial, as well as the `mine_github` function. I will then also add a warning pointing to the tutorial whenever the `all_branches` option is activated. Otherwise, I don't really see a good way to integrate it into git2net without changing the repository from within `mine_git_repo` which I want to avoid.

I will take care of this for the next release.

**Comment by gotec** [comment]
I have finally gotten around to a substantial rework of the tutorials, in which I also added more details on how to clone and crawl different branches of repositories.

@SebastianZug, I would highly appreciate it if you could have a brief look over the tutorial as you are (as far as I'm aware) the most active user of this feature. Feel free to close the issue if you find the new tutorial to be satisfactory for you and your students.

Cheers,
Christoph

**Comment by SebastianZug** [comment]
It was a good decision to separate and extend the examples. Good job!
