### ISSUE TITLE
Support for local repositories

### ISSUE THREAD

**Issue by SebastianZug** [gotec/git2net#18]
If you apply git2net on a local repository without remote origin, the crawling process crashes in line 1526.

```
   'repository': git_repo.repo.remotes.origin.url
```

Replacing the url reading from pydriller by a placeholder solves the problem. Should we integrate an additional parameter that implements this mechanism as a feature? 

Sebastian

**Comment by gotec** [comment]
Hi Sebastian,

I have just implemented a fix for this. Now, if no URL can be read from the repository, the local path to the repository will be used as identifier.

Would you mind trying if it works for you before I push a new version of git2net to PyPI?
You can do so by cloning a copy of git2net to your machine and then installing with `pip install -e .` from within the cloned repository.

Cheers,
Christoph

**Comment by SebastianZug** [comment]
Thanks for providing an official solution :-)

**Comment by gotec** [comment]
I have now released a version with this change in git2net 1.4.9. Feel free to reopen this issue in case there are any further issues with this.

Cheers,
Christoph
