### ISSUE TITLE
tqdm.auto minimum version required

### ISSUE THREAD

**Issue by verginer** [gotec/git2net#2]
`git2net` uses internally the `tqdm.auto` function for progress-bars.

The `auto` method is however not available in version 4.14.0. I do not know the exact version the `auto` was introduced in a more recent version, but I cant find it.
This would be a good case to specify a minimum version.

**Comment by gotec** [comment]
Hi Luca
thanks for letting me know! Upon further research `tqdm.auto` seems to have been introduced with v4.27.0 ([source](https://zenodo.org/record/1463045#.XLV4i0NoQUG)). I have updated the requirements in git2net v0.9.1 which is now available with pip.
Cheers,
Christoph
