### ISSUE TITLE
Tutorial notebook file does not work

### ISSUE THREAD

**Issue by ShushanArakelyan** [gotec/git2net#25]
**Describe the bug**
When getting to the network analysis and visualization portion of the notebook, I am first asked to add a call to disambiguate aliases:
`git2net.disambiguate_aliases_db(sqlite_db_file)`; After calling that and attempting to run the following line again I get an assertion error:
`t, node_info, edge_info = git2net.get_coediting_network(sqlite_db_file)`
>AssertionError                            Traceback (most recent call last)
<ipython-input-7-a92d317a0357> in <module>()
      1 git2net.disambiguate_aliases_db(sqlite_db_file)
----> 2 t, node_info, edge_info = git2net.get_coediting_network(sqlite_db_file)
      3 t
~/sachet/git2net/git2net/visualisation.py in get_coediting_network(sqlite_db_file, author_identifier, time_from, time_to)
    411                            row['pre_author'],
    412                            row['time'],
--> 413                            directed=True)
    414 
    415     return t, node_info, edge_info
~/.local/lib/python3.6/site-packages/pathpy/classes/temporal_network.py in add_edge(self, source, target, ts, directed, timestamp_format)
    375 
    376         """
--> 377         assert isinstance(ts, int) or isinstance(ts, str), 'Timestamp must either be string or int'
    378 
    379         if isinstance(ts, str):
AssertionError: Timestamp must either be string or int

**To Reproduce**
Run the notebook from the beginning, only skipping the private repo part.

**Comment by gotec** [comment]
Hi Shushan,

Thanks a lot for this information. Indeed I recently added author disambiguation as a new feature and did not have the time to add a new section in the tutorial. I will try to fix it as soon as possible.

Best,
Christoph

**Comment by gotec** [comment]
Hi Shushan,
Sorry for the delay, the tutorial is now back up and running. I noticed an issue with plotting the networks, which is likely due to a change in pathpy or a library it's using. I will fix this by upgrading to pathpy version 3 in the coming days.
Best,
Christoph
