### ISSUE TITLE
error in git, stops the whole process

### ISSUE THREAD

**Issue by wschuell** [gotec/git2net#37]
**Describe the bug**
git check-mailmap fails on a specific commit, where github reports the author as '-'
output: 
```
git.exc.GitCommandError: Cmd('git') failed due to: exit code(129)
  cmdline: git check-mailmap - <->
  stderr: 'error: unknown switch ` '
```

**To Reproduce**
```
import git2net

github_url = 'DefiLlama/DefiLlama-Adapters'
git_repo_dir = 'defillama_repo'
sqlite_db_file = 'defillama.db'
git2net.mine_github(github_url, git_repo_dir, sqlite_db_file,no_of_processes=1,commits=['c93164d34c0554cc06ff97c0290a572fff95a3b1'])

```

**Expected behavior**
Either treat the author as the string '-' (if possible) and/or treat in a similar way as the timeouts and print a message without interrupting the whole process (and letting other commits be processed). This second option could also be useful in a more general way.

**Comment by gotec** [comment]
Fixed in defd63880970b01bd9134565654ee8589ec1b479
