### ISSUE TITLE
RuntimeWarning: invalid value encountered in true_divide

### ISSUE THREAD

**Issue by MJimitater** [gotec/git2net#5]
Just curious what this warning is all about.. any ideas?

**Comment by gotec** [comment]
Thank's a lot for your message and sorry for the delayed response.
I have fixed a number of these warnings in the past. Usually they originated from functions from imported packages applied to e.g. empty files.
Could you provide me some code to replicate the issue? Then I can see what is causing it this time. I would like to eliminate all these warnings through proper if clauses at some point.

**Comment by MJimitater** [comment]
I mined the bitcoin repo from https://github.com/bitcoin/bitcoin

Im getting the warning when running this code (see also attachment):

`import git2net`
`sqlite_db_file = '~/bitcoin.db'`
`repo_dir = '~/bitcoin'`
`git2net.mine_git_repo(repo_dir, sqlite_db_file)`


![Bildschirmfoto vom 2019-11-20 23-59-04](https://user-images.githubusercontent.com/26901261/69286258-0eb62d00-0bf3-11ea-977a-3c3df0b7d90a.png)

From the attachment it seems like the `scipy` package is causing the warning, specifically the `/stats/_distn_infrastructure.py` function in line 2614. I checked this line, it contains `pk = 1.0*pk / np.sum(pk, axis=0)`, maybe that helps?

I am using a pip environment with a list of different packages (see attachment).







[packages.txt](https://github.com/gotec/git2net/files/3871918/packages.txt)

**Comment by gotec** [comment]
Thanks for the detailed information. I think I was able to track it down.

For the extraction, I only use scipy to compute the text entropy of a line of code (see the paper for details). The error you are referring to originates from passing a string of length 0 (an empty line) to the entropy function. I have fixed this error in one of the recent versions of git2net (1.1.1 if I recall correctly) by setting the text entropy to "None" for these cases. From your packages, I see that you are using git2net version 1.1.0. Just get the newest version of git2net by running ``pip install --upgrade git2net`` and the error should no longer occur.

I hope this helps!
Cheers,
Christoph

**Comment by MJimitater** [comment]
**Edit:**
When running git2net for a long time, I did notice however the same warning message occur, despite running all upgraded packages. Not sure why this is. Just for FYI
Cheers

---------------------------
Good catch! Works like a charm, thanks Christoph!

Greets,
Lucas

**Comment by gotec** [comment]
Finally found the problem. The warnings occurred for the very rare cases where lines only contain characters that are not in the UTF8 character set. These strings do not have length 0 (which I checked for) but contain no UTF8 characters. Thus, when computing the entropy still a division by 0 occurred.

I'll make sure the entire bitcoin repository runs through now and release an updated version of git2net later today.

**Comment by gotec** [comment]
Fixed in git2net 1.1.5 which I just released on PyPI. Again thanks for reporting this!
